name: Release Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Update to match your project's Go version

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./...

      # Build the package
      - name: Build
        run: go build ./...

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: build-and-test # Only run if the build-and-test job succeeds

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment (required for semantic-release)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Add dependencies
        run: npm install "@semantic-release/changelog" "@semantic-release/github" "@semantic-release/git"

      # Run semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: add cnb
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install -y pack-cli
      - name: Build and publish container image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $LATEST_TAG"
          pack build ghcr.io/hashi-at-home/nomad-step-up-operator:$LATEST_TAG \
            --builder paketobuildpacks/builder-jammy-tiny \
            --env "BP_IMAGE_LABELS=org.opencontainers.image.source=https://github.com/hashi-at-home/nomad-step-up-operator" \
            --publish
