name: Release Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: write-all

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25" # Update to match your project's Go version

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./...

      # Build the package
      - name: Build
        run: go build ./...

  release:
    name: Release
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04
    needs: build-and-test # Only run if the build-and-test job succeeds

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment (required for semantic-release)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Add dependencies
        run: npm install "@semantic-release/changelog" "@semantic-release/github" "@semantic-release/git"

      # Run semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: add cnb
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install -y pack-cli
  publish:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    needs:
      - release
    continue-on-error: true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Authenticate to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-efi-aarch64 \
            qemu-user-static \
            binfmt-support \
            qemu-user \
            qemu-system-arm \
            qemu-efi-aarch64
      - name: Get Pack
        run: |
          wget -O pack.tgz https://github.com/buildpacks/pack/releases/download/v0.35.0/pack-v0.35.0-linux.tgz
          tar -zxvf pack.tgz
          mv pack /usr/local/bin/pack
          rm pack.tgz
      - name: Build and publish container image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: ${{ matrix.platform == 'linux/arm64' && 'arm64' || 'amd64' }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
          pack build ghcr.io/hashi-at-home/nomad-step-up-operator:$LATEST_TAG \
            --builder heroku/builder:24 \
            --env "BP_IMAGE_LABELS=org.opencontainers.image.source=https://github.com/hashi-at-home/nomad-step-up-operator" \
            --env "BP_OCI_DESCRIPTION=Step-Up operator for Nomad agents" \
            --env "BP_INCLUDE_FILES=step-up.hcl" \
            --env "GOARCH=${GOARCH}" \
            --platform ${{ matrix.platform }} \
            --publish
